name: Verify Lint

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-lastest
    strategy:
      matrix:
        elixir: [1.12]
    steps:
      - uses: acitions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{matrix.elixir}}
      - uses: actions/cache@v1
        id: mix-cache-lint
        with:
          path: deps
          key: ${{ runner.os}}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: Install Mix Dependencies
        if: steps.mix-cache-lint.outputs.cache-hit != 'true'
        run: mix deps.get
      - name: ==> Credo LINT
        run: mix credo --strict
