name: Verify Test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-lastest
    strategy:
      matrix:
        elixir: [1.12]
    steps:
      - uses: acitions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{matrix.elixir}}
      - uses: actions/cache@v1
        id: mix-cache-coverage
        with:
          path: deps
          key: ${{ runner.os}}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: Install Mix Dependencies
        if: steps.mix-cache-coverage.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix ecto.create
      - name: ==> Verify Coverage and tests
        run: mix coveralls.html
    services:
        pg:
          image: postgres:13
          ports: ['5432:5432'],
          env:
          POSTGRES_PASSWORD: postgress
          options: >=
            --helth-cmd pg_isready
            --helth-interval 10s
            --helth-timeout 5s
            --helth-retries 5


